// This file is auto-generated by the Supabase CLI and defines the database types
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      refugee_profiles: {
        Row: {
          id: string
          email: string
          password: string
          first_name: string
          last_name: string
          phone: string | null
          date_of_birth: string | null
          gender: string
          country_of_origin: string
          current_location: string
          languages: string[]
          skills: string[]
          bio: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          password: string
          first_name: string
          last_name: string
          phone?: string | null
          date_of_birth?: string | null
          gender?: string
          country_of_origin: string
          current_location: string
          languages?: string[]
          skills?: string[]
          bio?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          password?: string
          first_name?: string
          last_name?: string
          phone?: string | null
          date_of_birth?: string | null
          gender?: string
          country_of_origin?: string
          current_location?: string
          languages?: string[]
          skills?: string[]
          bio?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
}
